In [12]:
import torch
from torch.autograd import Variable

tensor=torch.ones((2,3),requires_grad=True)
#variable = Variable(tensor, requires_grad=True) 

print(tensor)
#print(variable)

t_out = torch.mean(tensor*tensor)
print(t_out)

t_out.backward()
print(t_out.grad)


tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor(1., grad_fn=<MeanBackward0>)
None


<ipython-input-12-3cc3f7e003bc>:14: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information.
  print(t_out.grad)


In [6]:
import torch
x=torch.Tensor(2,3)
print(x,'\n')
y=torch.Tensor(4,2,3)
print(y)


tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

tensor([[[8.9082e-39, 9.8265e-39, 9.4592e-39],
         [1.0561e-38, 1.0653e-38, 1.0469e-38]],

        [[9.5510e-39, 9.0918e-39, 9.1837e-39],
         [8.4490e-39, 8.7245e-39, 1.0102e-38]],

        [[1.0653e-38, 8.7245e-39, 9.0918e-39],
         [4.6838e-39, 4.1327e-39, 9.6429e-39]],

        [[8.7245e-39, 1.0010e-38, 4.9593e-39],
         [4.2245e-39, 1.1112e-38, 1.4013e-43]]])


False